replicaCount: 1

image:
  repository: backendservices151.azurecr.io/backend-java/java-service
  tag: v1

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
