replicaCount: 2

image:
  repository: backendservices151.azurecr.io/backend-java/java-service
  tag: v1

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
